### ISSUE TITLE
Tarball download links changed

### ISSUE THREAD

**Issue by ghost** [c-ares/c-ares.github.io#2]
After the move form Daniel's infrastructure to github pages the download links to existing versions unfortunately changed.

Previously: http://c-ares.haxx.se/download/c-ares-1.28.1.tar.gz
Now: https://github.com/c-ares/c-ares/releases/download/cares-1_28_1/c-ares-1.28.1.tar.gz

The old links are used in distro build scripts and embedded distro build systems (i.e. openembedded, buildroot) and while fixing this individually is of course trivial, in general this creates a lot of churn and makes (re-) building older package versions unnecessarily annoying.

Is there a chance for adding redirects from the old to the new location, at least for existing releases?

**Comment by bradh352** [comment]
I don't think its possible.  A quick google says GitHub Pages doesn't support .htaccess files, so that means we can't write redirect rules for those files...
